### ISSUE TITLE
Can't load image directory 

### ISSUE THREAD

**Issue by dakota-hawkins** [nadavyayon/Intensify3D#2]
Hi there!

I recently read your paper on Intensify3D, and got very excited about the possibility of incorporating it into some of our image analysis. 

I'm familiar with -- but not super practiced in MATLAB -- so I apologize if this issue is easily solvable and it's my own lack of knowledge.

I've cloned the most recent version of `Intensify3D` (commit #d384ec0, v2.0), installed MATLAB 2020a, and downloaded the simulated sample data. When I run the gui script, the window opens as expected, but when I select an image directory to use I receive the following error:

```
Unrecognized function or variable 'StringArray'.

Error in User_GUI_Intensify3D>ParentFolderBrowse_Callback (line 115)
set(handles.listbox1, 'string', string(StringArray));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in User_GUI_Intensify3D (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)User_GUI_Intensify3D('ParentFolderBrowse_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

Seemingly coming from this part of the code:

```Matlab
function ParentFolderBrowse_Callback(hObject, eventdata, handles)
% hObject    handle to ParentFolderBrowse (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
Folder = uigetdir(cd,'MATLAB Root Directory');
set(handles.StackFolder,'string',Folder);
import java.lang.*;
r=Runtime.getRuntime;
ncpu=r.availableProcessors;
Directories = dir(Folder);
DirectoryIndex = find([Directories.isdir])'; 
for i = 1:length(DirectoryIndex)-2
    StringArray{i,1} = [num2str(i),') ',Directories(DirectoryIndex(i+2)).name];
end
```

Again, I'm not overly familiar with MATLAB but it seems the variable `StringArray` needs to be instantiated prior to the for loop?

I ran into similar but distinct issues trying to load images with the 1.1 release, but I was working on my linux machine, and was unsure if that was causing the issue. 

For replication:

1. The above `StringArray` error occurred both on Windows 10 + Elementary Linux
2. Matlab version 2020a was used for both OSes.

To ensure it's not a version or toolbox issue on my end, would it be possible to get a list of 1. Tested MATLAB versions, and 2. List of used/assumed toolboxes?

Thanks so much, and looking forward to using your software!

Dakota

**Comment by nadavyayon** [comment]
Dear Dakota 

First of all I would like to apologize for this very late response the email address i set for notifications was wrong. 
As for your error, I got this error message when the folder you select contains no directories in it. Intensify3D+ is intended to provide normalization solutions between samples so the "parent" directory contains subfolders that represent samples. 

If you have one sample simply put it in an additional folder and select the one containing it. or you can use Intensify3D https://github.com/nadavyayon/Intensify3D/releases/tag/v1.1 that is designed for a single sample 

As to the MATLAB version I also used  2020a but I need to further check if I can see exactly which toolboxes it uses. 
I will also add a compiled standalone version of intensify3D+ and hopefully this will be more robust. 

Sorry again and would love to hear if this solved your problem 

Nadav
